# -*- coding: utf-8 -*-
"""Swargam Sailaxmi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OAz12RCmfdRQ4t6Yn4wXFUCJhGLVuzmO

Logic Building Task - 1

1.user Login Check
"""

username = "admin"
password = "1234"
username = input("Enter username: ")
password = input("Enter password: ")
if username == username and password == password:
  print("Login Successful")
else:
  print("Invalid Credentials")

"""2.Pass/Fail Analyzer"""

marks = [45, 78, 90, 33, 60]
num_pass = 0
for i in marks:
  if i >= 50:
    num_pass = num_pass + 1
fail = len(marks) - num_pass
print("Pass:", num_pass)
print("Fail:", fail)

"""3.Simple Data Cleaner"""

names = ["Alice", "bob", "CHARLIE"]
cleaned_names = []
for name in names:
  cleaned_name = name.strip().lower()
  cleaned_names.append(cleaned_name)
print(cleaned_names)

"""4.Message Length Analyzer"""

messages = ["Hi", "Welcome to the platform", "OK"]
for message in messages:
  length = len(message)
  print(f"Message: '{message}' (Length: {length})")
  if length > 10:
     print("This message is longer than 10 characters!")

"""5.Error Message Detector"""

logs = ["INFO", "ERROR", "WARNING", "ERROR"]
error_count = 0
for entries in logs:
  if entries == "ERROR":
    error_count += 1
print(f"Number of ERROR messages: {error_count}")